version: '3.9'

services:
  postgres-db:
    image: postgres:16.0-alpine
    platform: linux/arm64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: opdee
      POSTGRES_PASSWORD: opdee
      POSTGRES_DB: opdee
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opdee-network

  spring-app:
    image: opdee:latest
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/opdee
    depends_on:
      - postgres-db
    networks:
      - opdee-network

volumes:
  postgres_data:
    driver: local

networks:
  opdee-network:
    driver: bridge