name: CI — OPDEE-API

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build (sem testes)
        run: ./mvnw -B package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: opdee-api-jar
          path: target/*.jar
          retention-days: 7
